[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "1.90.0"
components = ["rustfmt", "cargo", "clippy", "rust-analyzer", "llvm-tools", "rustc"]
profile = "default"
targets = ["wasm32-unknown-unknown", "wasm32-wasip1"]
