name: devenv
description: "Setup development environment with devenv"
inputs:
  github-token:
    description: Provide a github token
    required: true

runs:
  using: composite
  steps:
    # - name: free disk space (ubuntu)
    #   uses: jlumbroso/free-disk-space@v1.3.1
    #   with:
    #     # this might remove tools that are actually needed,
    #     # if set to "true" but frees about 6 GB
    #     tool-cache: true
    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: enable cachix
      uses: cachix/cachix-action@v16
      with:
        name: wasm_solana
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

    - name: install devenv.sh
      run: nix profile install nixpkgs#devenv
      shell: bash

    - name: build developer environment
      run: devenv test
      shell: bash

    - name: cache rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v0-rust"
        key: ${{ runner.os }}

    - name: cache cargo binaries
      uses: actions/cache@v4
      with:
        path: ./.bin
        key: ${{ runner.os }}-cargo-bin-v1-${{ env.RUSTUP_TOOLCHAIN }}-${{ hashFiles('rust-toolchain.toml', 'Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-bin-v1-

    - name: cache eget
      uses: actions/cache@v4
      with:
        path: ./.eget/bin
        key: ${{ runner.os }}-eget-v1-${{ hashFiles('.eget/.eget.toml') }}
        restore-keys: |
          ${{ runner.os }}-eget-v1-

    - name: install dependencies
      run: install:all
      shell: devenv shell bash -- -e {0}
