name: devenv
description: "Setup development environment with devenv"
inputs:
  github-token:
    description: Provide a github token
    required: true
  cache-version:
    description: The version of the cache to use.
    required: false
    default: "v1"

runs:
  using: composite
  steps:
    - name: free disk space (ubuntu)
      uses: wimpysworld/nothing-but-nix@main
      with:
        hatchet-protocol: "cleave"
        witness-carnage: true

    # - name: install determinate nix
    #   uses: DeterminateSystems/nix-installer-action@v20
    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: enable cachix
      uses: cachix/cachix-action@v16
      with:
        name: devenv

    - name: install devenv.sh
      run: nix profile add nixpkgs#devenv
      shell: bash

    - name: build developer environment
      run: devenv test
      shell: bash

    - name: cache rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "${{ inputs.cache-version }}"
        key: ${{ runner.os }}-rust

    - name: cache cargo binaries
      uses: actions/cache@v4
      with:
        path: ./.bin
        key: ${{ runner.os }}-cargo-bin-${{ inputs.cache-version }}-${{ env.RUSTUP_TOOLCHAIN }}-${{ hashFiles('rust-toolchain.toml', 'Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-bin-${{ inputs.cache-version }}-

    - name: cache eget
      uses: actions/cache@v4
      with:
        path: ./.eget/bin
        key: ${{ runner.os }}-eget-${{ inputs.cache-version }}-${{ hashFiles('.eget/.eget.toml') }}
        restore-keys: |
          ${{ runner.os }}-eget-${{ inputs.cache-version }}-

    # - name: install dependencies
    #   run: install:all
    #   shell: devenv shell bash -- -e {0}
