name: devenv
description: "Setup development environment with devenv"
inputs:
  github-token:
    description: Provide a github token
    required: true
  cache-version:
    description: The version of the cache to use.
    required: false
    default: "v1"

runs:
  using: composite
  steps:
    - name: cache rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "${{ inputs.cache-version }}"
        shared-key: "main"
        cache-on-failure: ${{ github.event.name == 'push' && true || false  }}
        save-if: ${{ github.event.name == 'push' && 'true' || 'false'  }}

    - name: cache cargo binaries
      uses: actions/cache@v4
      with:
        path: ./.bin
        key: ${{ runner.os }}-cargo-bin-${{ inputs.cache-version }}-${{ env.RUSTUP_TOOLCHAIN }}-${{ hashFiles('rust-toolchain.toml', 'Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-bin-${{ inputs.cache-version }}-

    - name: cache eget
      uses: actions/cache@v4
      with:
        path: ./.eget/bin
        key: ${{ runner.os }}-eget-${{ inputs.cache-version }}-${{ hashFiles('.eget/.eget.toml') }}
        restore-keys: |
          ${{ runner.os }}-eget-${{ inputs.cache-version }}-

    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: setup nix environment
      run: |
        env
        echo "LIBCLANG_PATH=$LIBCLANG_PATH"
        ls -al $LIBCLANG_PATH
        nix profile add --accept-flake-config nixpkgs#cachix
        cachix use devenv
        nix profile add nixpkgs#devenv
      shell: bash

    - name: install dependencies
      run: install:cargo:bin
      shell: devenv shell -c -- bash -e {0}

    - name: debug
      run: |
        env
        echo "LIBCLANG_PATH=$LIBCLANG_PATH"
        ls -al $LIBCLANG_PATH
        echo "DEVENV_PROFILE=$DEVENV_PROFILE"
        ls -al $DEVENV_PROFILE/lib
      shell: devenv shell -c -- bash -e {0}
